import library

In [131]:
import pandas as pd
import os
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

Extract

In [132]:
covid = pd.read_csv("C:/Users/muhammad fadhli/Documents/MySkill/covid_19_indonesia_time_series_all.csv")

In [133]:
covid.head()

,Date,Location ISO Code,Location,New Cases,New Deaths,New Recovered,New Active Cases,Total Cases,Total Deaths,Total Recovered,...,Latitude,New Cases per Million,Total Cases per Million,New Deaths per Million,Total Deaths per Million,Total Deaths per 100rb,Case Fatality Rate,Case Recovered Rate,Growth Factor of New Cases,Growth Factor of New Deaths
0,3/1/2020,ID-JK,DKI Jakarta,2,0,0,2,39,20,75,...,-6.204699,0.18,3.60,0.0,1.84,0.18,51.28%,192.31%,NaN,NaN
1,3/2/2020,ID-JK,DKI Jakarta,2,0,0,2,41,20,75,...,-6.204699,0.18,3.78,0.0,1.84,0.18,48.78%,182.93%,1.0,1.0
2,3/2/2020,IDN,Indonesia,2,0,0,2,2,0,0,...,-0.789275,0.01,0.01,0.0,0.00,0.00,0.00%,0.00%,NaN,NaN
3,3/2/2020,ID-RI,Riau,1,0,0,1,1,0,1,...,0.511648,0.16,0.16,0.0,0.00,0.00,0.00%,100.00%,NaN,NaN
4,3/3/2020,ID-JK,DKI Jakarta,2,0,0,2,43,20,75,...,-6.204699,0.18,3.96,0.0,1.84,0.18,46.51%,174.42%,1.0,1.0

In [134]:
covid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31822 entries, 0 to 31821
Data columns (total 38 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         31822 non-null  object
 1   Location ISO Code            31822 non-null  object
 2   Location                     31822 non-null  object
 3   New Cases                    31822 non-null  int64
 4   New Deaths                   31822 non-null  int64
 5   New Recovered                31822 non-null  int64
 6   New Active Cases             31822 non-null  int64
 7   Total Cases                  31822 non-null  int64
 8   Total Deaths                 31822 non-null  int64
 9   Total Recovered              31822 non-null  int64
 10  Total Active Cases           31822 non-null  int64
 11  Location Level               31822 non-null  object
 12  City or Regency              0 non-null      float64
 13  Province                     30893 non-null  object
 14  Country                      31822 non-null  object
 15  Continent                    31822 non-null  object
 16  Island                       30893 non-null  object
 17  Time Zone                    30893 non-null  object
 18  Special Status               4558 non-null   object
 19  Total Regencies              31822 non-null  int64
 20  Total Cities                 30921 non-null  float64
 21  Total Districts              31822 non-null  int64
 22  Total Urban Villages         30918 non-null  float64
 23  Total Rural Villages         30893 non-null  float64
 24  Area (km2)                   31822 non-null  int64
 25  Population                   31822 non-null  int64
 26  Population Density           31822 non-null  float64
 27  Longitude                    31822 non-null  float64
 28  Latitude                     31822 non-null  float64
 29  New Cases per Million        31822 non-null  float64
 30  Total Cases per Million      31822 non-null  float64
 31  New Deaths per Million       31822 non-null  float64
 32  Total Deaths per Million     31822 non-null  float64
 33  Total Deaths per 100rb       31822 non-null  float64
 34  Case Fatality Rate           31822 non-null  object
 35  Case Recovered Rate          31822 non-null  object
 36  Growth Factor of New Cases   29883 non-null  float64
 37  Growth Factor of New Deaths  28375 non-null  float64
dtypes: float64(14), int64(12), object(12)
memory usage: 9.2+ MB

In [135]:
covid['Date'] = pd.to_datetime(covid['Date'])

In [136]:
covid['Date']

0       2020-03-01
1       2020-03-02
2       2020-03-02
3       2020-03-02
4       2020-03-03
           ...
31817   2022-09-15
31818   2022-09-15
31819   2022-09-15
31820   2022-09-15
31821   2022-09-16
Name: Date, Length: 31822, dtype: datetime64[ns]

Transformation

In [137]:
covid.isna().sum()

Date                               0
Location ISO Code                  0
Location                           0
New Cases                          0
New Deaths                         0
New Recovered                      0
New Active Cases                   0
Total Cases                        0
Total Deaths                       0
Total Recovered                    0
Total Active Cases                 0
Location Level                     0
City or Regency                31822
Province                         929
Country                            0
Continent                          0
Island                           929
Time Zone                        929
Special Status                 27264
Total Regencies                    0
Total Cities                     901
Total Districts                    0
Total Urban Villages             904
Total Rural Villages             929
Area (km2)                         0
Population                         0
Population Density                 0
Longitude                          0
Latitude                           0
New Cases per Million              0
Total Cases per Million            0
New Deaths per Million             0
Total Deaths per Million           0
Total Deaths per 100rb             0
Case Fatality Rate                 0
Case Recovered Rate                0
Growth Factor of New Cases      1939
Growth Factor of New Deaths     3447
dtype: int64

In [138]:
covid = covid.drop('City or Regency', axis = 1)

In [139]:
covid.isna().sum()

Date                               0
Location ISO Code                  0
Location                           0
New Cases                          0
New Deaths                         0
New Recovered                      0
New Active Cases                   0
Total Cases                        0
Total Deaths                       0
Total Recovered                    0
Total Active Cases                 0
Location Level                     0
Province                         929
Country                            0
Continent                          0
Island                           929
Time Zone                        929
Special Status                 27264
Total Regencies                    0
Total Cities                     901
Total Districts                    0
Total Urban Villages             904
Total Rural Villages             929
Area (km2)                         0
Population                         0
Population Density                 0
Longitude                          0
Latitude                           0
New Cases per Million              0
Total Cases per Million            0
New Deaths per Million             0
Total Deaths per Million           0
Total Deaths per 100rb             0
Case Fatality Rate                 0
Case Recovered Rate                0
Growth Factor of New Cases      1939
Growth Factor of New Deaths     3447
dtype: int64

In [140]:
covid['Province']

0             DKI Jakarta
1             DKI Jakarta
2                     NaN
3                    Riau
4             DKI Jakarta
               ...
31817      Sulawesi Utara
31818      Sumatera Barat
31819    Sumatera Selatan
31820      Sumatera Utara
31821                 NaN
Name: Province, Length: 31822, dtype: object

In [141]:
covid.isna().sum()

Date                               0
Location ISO Code                  0
Location                           0
New Cases                          0
New Deaths                         0
New Recovered                      0
New Active Cases                   0
Total Cases                        0
Total Deaths                       0
Total Recovered                    0
Total Active Cases                 0
Location Level                     0
Province                         929
Country                            0
Continent                          0
Island                           929
Time Zone                        929
Special Status                 27264
Total Regencies                    0
Total Cities                     901
Total Districts                    0
Total Urban Villages             904
Total Rural Villages             929
Area (km2)                         0
Population                         0
Population Density                 0
Longitude                          0
Latitude                           0
New Cases per Million              0
Total Cases per Million            0
New Deaths per Million             0
Total Deaths per Million           0
Total Deaths per 100rb             0
Case Fatality Rate                 0
Case Recovered Rate                0
Growth Factor of New Cases      1939
Growth Factor of New Deaths     3447
dtype: int64

In [142]:
covid['Island'].unique()

array(['Jawa', nan, 'Sumatera', 'Sulawesi', 'Nusa Tenggara', 'Kalimantan',
       'Maluku', 'Papua'], dtype=object)

In [143]:
covid['Time Zone'].unique()

array(['UTC+07:00', nan, 'UTC+08:00', 'UTC+09:00'], dtype=object)

In [144]:
covid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31822 entries, 0 to 31821
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         31822 non-null  datetime64[ns]
 1   Location ISO Code            31822 non-null  object
 2   Location                     31822 non-null  object
 3   New Cases                    31822 non-null  int64
 4   New Deaths                   31822 non-null  int64
 5   New Recovered                31822 non-null  int64
 6   New Active Cases             31822 non-null  int64
 7   Total Cases                  31822 non-null  int64
 8   Total Deaths                 31822 non-null  int64
 9   Total Recovered              31822 non-null  int64
 10  Total Active Cases           31822 non-null  int64
 11  Location Level               31822 non-null  object
 12  Province                     30893 non-null  object
 13  Country                      31822 non-null  object
 14  Continent                    31822 non-null  object
 15  Island                       30893 non-null  object
 16  Time Zone                    30893 non-null  object
 17  Special Status               4558 non-null   object
 18  Total Regencies              31822 non-null  int64
 19  Total Cities                 30921 non-null  float64
 20  Total Districts              31822 non-null  int64
 21  Total Urban Villages         30918 non-null  float64
 22  Total Rural Villages         30893 non-null  float64
 23  Area (km2)                   31822 non-null  int64
 24  Population                   31822 non-null  int64
 25  Population Density           31822 non-null  float64
 26  Longitude                    31822 non-null  float64
 27  Latitude                     31822 non-null  float64
 28  New Cases per Million        31822 non-null  float64
 29  Total Cases per Million      31822 non-null  float64
 30  New Deaths per Million       31822 non-null  float64
 31  Total Deaths per Million     31822 non-null  float64
 32  Total Deaths per 100rb       31822 non-null  float64
 33  Case Fatality Rate           31822 non-null  object
 34  Case Recovered Rate          31822 non-null  object
 35  Growth Factor of New Cases   29883 non-null  float64
 36  Growth Factor of New Deaths  28375 non-null  float64
dtypes: datetime64[ns](1), float64(13), int64(12), object(11)
memory usage: 9.0+ MB

In [145]:
covid.isna().sum()

Date                               0
Location ISO Code                  0
Location                           0
New Cases                          0
New Deaths                         0
New Recovered                      0
New Active Cases                   0
Total Cases                        0
Total Deaths                       0
Total Recovered                    0
Total Active Cases                 0
Location Level                     0
Province                         929
Country                            0
Continent                          0
Island                           929
Time Zone                        929
Special Status                 27264
Total Regencies                    0
Total Cities                     901
Total Districts                    0
Total Urban Villages             904
Total Rural Villages             929
Area (km2)                         0
Population                         0
Population Density                 0
Longitude                          0
Latitude                           0
New Cases per Million              0
Total Cases per Million            0
New Deaths per Million             0
Total Deaths per Million           0
Total Deaths per 100rb             0
Case Fatality Rate                 0
Case Recovered Rate                0
Growth Factor of New Cases      1939
Growth Factor of New Deaths     3447
dtype: int64

In [146]:
covid['Province'] = covid['Province'].fillna('No Data')
covid['Island'] = covid['Island'].fillna('No Data')
covid['Time Zone'] = covid['Time Zone'].fillna('No Data')
covid['Special Status'] = covid['Special Status'].fillna('No Data')
covid['Total Cities'].fillna(covid['Total Cities'].mean(), inplace=True)
covid['Total Urban Villages'].fillna(covid['Total Urban Villages'].mean(), inplace=True)
covid['Total Rural Villages'].fillna(covid['Total Rural Villages'].mean(), inplace=True)

In [147]:
covid['Growth Factor of New Cases'].fillna(covid['Growth Factor of New Cases'].mean(), inplace=True)
covid['Growth Factor of New Deaths'].fillna(covid['Growth Factor of New Deaths'].mean(), inplace=True)

In [149]:
covid.isna().sum()

Date                           0
Location ISO Code              0
Location                       0
New Cases                      0
New Deaths                     0
New Recovered                  0
New Active Cases               0
Total Cases                    0
Total Deaths                   0
Total Recovered                0
Total Active Cases             0
Location Level                 0
Province                       0
Country                        0
Continent                      0
Island                         0
Time Zone                      0
Special Status                 0
Total Regencies                0
Total Cities                   0
Total Districts                0
Total Urban Villages           0
Total Rural Villages           0
Area (km2)                     0
Population                     0
Population Density             0
Longitude                      0
Latitude                       0
New Cases per Million          0
Total Cases per Million        0
New Deaths per Million         0
Total Deaths per Million       0
Total Deaths per 100rb         0
Case Fatality Rate             0
Case Recovered Rate            0
Growth Factor of New Cases     0
Growth Factor of New Deaths    0
dtype: int64

In [150]:
covid['Area (km2)'].unique()

array([    664, 1916907,   87024,   35378,    9663,   32801,   38068,
          5780,  129067,    3133,   72981,   47803,    8202,   46717,
         50058,   46914,  319036,   31983,   91592,   57956,  153565,
         34624,   61841,   13892,   42013,  102955,   75468,   16787,
        147307,   38744,   16424,   19919,   18572,   48718,   11257],
      dtype=int64)

In [151]:
covid.rename(columns={'Location ISO Code': 'Location_ISO_Code', 
                      'New Cases': 'New_Cases',
                      'New Deaths': 'New_Deaths',
                      'New Recovered': 'New_Recovered',
                      'New Active Cases': 'New_Active_Cases',
                      'Total Cases': 'Total_Cases',
                      'Total Deaths': 'Total_Deaths',
                      'Total Recovered': 'Total_Recovered',
                      'Total Active Cases': 'Total_Active_Cases',
                      'Location Level': 'Location_Level',
                      'Time Zone': 'Time_Zone',
                      'Special Status': 'Special_Status',
                      'Total Regencies': 'Total_Regencies',
                      'Total Cities': 'Total_Cities',
                      'Total Districts': 'Total_Districts',
                      'Total Urban Villages': 'Total_Urban_Villages',
                      'Total Rural Villages': 'Total_Rural_Villages',
                      'Area (km2)': 'Area_km2',
                      'Population Density': 'Population_Density',
                      'New Cases per Million': 'New_Cases_per_Million',
                      'Total Cases per Million': 'Total_Cases_per_Million',
                      'New Deaths per Million': 'New_Deaths_per_Million',
                      'Total Deaths per Million': 'Total_Deaths_per_Million',
                      'Total Deaths per 100rb': 'Total_Deaths_per_100rb',
                      'Case Fatality Rate': 'Case_Fatality_Rate',
                      'Case Recovered Rate': 'Case_Recovered_Rate',
                      'Growth Factor of New Cases': 'Growth_Factor_of_New_Cases',
                      'Growth Factor of New Deaths': 'Growth_Factor_of_New_Deaths'
}, inplace=True)

In [152]:
covid.head()

,Date,Location_ISO_Code,Location,New_Cases,New_Deaths,New_Recovered,New_Active_Cases,Total_Cases,Total_Deaths,Total_Recovered,...,Latitude,New_Cases_per_Million,Total_Cases_per_Million,New_Deaths_per_Million,Total_Deaths_per_Million,Total_Deaths_per_100rb,Case_Fatality_Rate,Case_Recovered_Rate,Growth_Factor_of_New_Cases,Growth_Factor_of_New_Deaths
0,2020-03-01,ID-JK,DKI Jakarta,2,0,0,2,39,20,75,...,-6.204699,0.18,3.60,0.0,1.84,0.18,51.28%,192.31%,1.326795,1.033834
1,2020-03-02,ID-JK,DKI Jakarta,2,0,0,2,41,20,75,...,-6.204699,0.18,3.78,0.0,1.84,0.18,48.78%,182.93%,1.000000,1.000000
2,2020-03-02,IDN,Indonesia,2,0,0,2,2,0,0,...,-0.789275,0.01,0.01,0.0,0.00,0.00,0.00%,0.00%,1.326795,1.033834
3,2020-03-02,ID-RI,Riau,1,0,0,1,1,0,1,...,0.511648,0.16,0.16,0.0,0.00,0.00,0.00%,100.00%,1.326795,1.033834
4,2020-03-03,ID-JK,DKI Jakarta,2,0,0,2,43,20,75,...,-6.204699,0.18,3.96,0.0,1.84,0.18,46.51%,174.42%,1.000000,1.000000

In [153]:
covid.duplicated().sum()

0

Load

In [154]:
from google.cloud import bigquery

In [155]:
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = "C:/Users/muhammad fadhli/Documents/MySkill/aqueous-freedom-398208-cfe0d4e567f2.json"

In [156]:
covid.to_gbq(destination_table ='portfolio_fadhli.covid', project_id ='aqueous-freedom-398208', if_exists='replace')

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 [00:00<?, ?it/s]

In [157]:
covid['Province']

0             DKI Jakarta
1             DKI Jakarta
2                 No Data
3                    Riau
4             DKI Jakarta
               ...
31817      Sulawesi Utara
31818      Sumatera Barat
31819    Sumatera Selatan
31820      Sumatera Utara
31821             No Data
Name: Province, Length: 31822, dtype: object

In [158]:
covid

,Date,Location_ISO_Code,Location,New_Cases,New_Deaths,New_Recovered,New_Active_Cases,Total_Cases,Total_Deaths,Total_Recovered,...,Latitude,New_Cases_per_Million,Total_Cases_per_Million,New_Deaths_per_Million,Total_Deaths_per_Million,Total_Deaths_per_100rb,Case_Fatality_Rate,Case_Recovered_Rate,Growth_Factor_of_New_Cases,Growth_Factor_of_New_Deaths
0,2020-03-01,ID-JK,DKI Jakarta,2,0,0,2,39,20,75,...,-6.204699,0.18,3.60,0.0,1.84,0.18,51.28%,192.31%,1.326795,1.033834
1,2020-03-02,ID-JK,DKI Jakarta,2,0,0,2,41,20,75,...,-6.204699,0.18,3.78,0.0,1.84,0.18,48.78%,182.93%,1.000000,1.000000
2,2020-03-02,IDN,Indonesia,2,0,0,2,2,0,0,...,-0.789275,0.01,0.01,0.0,0.00,0.00,0.00%,0.00%,1.326795,1.033834
3,2020-03-02,ID-RI,Riau,1,0,0,1,1,0,1,...,0.511648,0.16,0.16,0.0,0.00,0.00,0.00%,100.00%,1.326795,1.033834
4,2020-03-03,ID-JK,DKI Jakarta,2,0,0,2,43,20,75,...,-6.204699,0.18,3.96,0.0,1.84,0.18,46.51%,174.42%,1.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31817,2022-09-15,ID-SA,Sulawesi Utara,37,0,0,37,52770,1213,50997,...,1.259638,14.01,19974.38,0.0,459.14,45.91,2.30%,96.64%,2.850000,1.000000
31818,2022-09-15,ID-SB,Sumatera Barat,13,0,3,10,104640,2371,102066,...,-0.850253,2.36,18959.11,0.0,429.59,42.96,2.27%,97.54%,6.500000,1.000000
31819,2022-09-15,ID-SS,Sumatera Selatan,16,0,1,15,82198,3376,78510,...,-3.216212,1.95,10002.74,0.0,410.83,41.08,4.11%,95.51%,3.200000,1.000000
31820,2022-09-15,ID-SU,Sumatera Utara,50,0,5,45,158866,3288,154924,...,2.191894,3.36,10680.15,0.0,221.04,22.10,2.07%,97.52%,1.920000,1.000000
31821,2022-09-16,IDN,Indonesia,2358,27,2997,-666,6405044,157876,6218708,...,-0.789275,8.89,24153.07,0.1,595.34,59.53,2.46%,97.09%,0.890000,1.290000

In [161]:
bigquery_client = bigquery.Client()

In [162]:
query1 = """
SELECT 
  Date, 
  SUM(New_Cases) AS total_kasus 
FROM 
  `aqueous-freedom-398208.portfolio_fadhli.covid`
GROUP BY 
  Date
ORDER BY 
  Date DESC
LIMIT 30
"""
result1 = bigquery_client.query(query1)